[package]
name = "vertex"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true

[dependencies]
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu" }
common = { workspace = true }
